### ISSUE TITLE
Third-party applications

### ISSUE THREAD

**Issue by fmoliveira** [rpg-maker-repo/rpg-maker-repo.github.io#10]
Mike, could you please check if third-party application restrictions is not enabled or add [Codeship](https://codeship.com/) as a trusted application? I'll use it for continuous deploying the website.

How to check that: https://help.github.com/articles/enabling-third-party-application-restrictions-for-your-organization/

/cc @deusprogrammer

**Comment by deusprogrammer** [comment]
Done =).
